# Generated by Django 4.1.4 on 2022-12-14 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_uz", models.TextField()),
                ("text_ru", models.TextField()),
                ("text_en", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Biz haqimizda",
                "verbose_name_plural": "Biz haqimizda",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=150)),
                ("name_ru", models.CharField(max_length=150)),
                ("name_en", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("comment_text", models.TextField()),
                ("username", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Kommentariya",
                "verbose_name_plural": "Kommentariyalar",
            },
        ),
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("heading_uz", models.CharField(max_length=500)),
                ("heading_ru", models.CharField(max_length=500)),
                ("heading_en", models.CharField(blank=True, max_length=500, null=True)),
                ("text_uz", models.TextField()),
                ("text_ru", models.TextField()),
                ("text_en", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone_number", models.CharField(max_length=100)),
                ("lang_id", models.IntegerField()),
                ("chat_id", models.IntegerField()),
            ],
            options={"verbose_name": "Mijoz", "verbose_name_plural": "Mijozlar",},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=150)),
                ("name_ru", models.CharField(max_length=150)),
                ("name_en", models.CharField(blank=True, max_length=150, null=True)),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("description_en", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot_app.category",
                    ),
                ),
            ],
            options={"verbose_name": "Mahsulot", "verbose_name_plural": "Mahsulotlar",},
        ),
    ]
